[profiles.sway]
posthooks = ["sway reload && makoctl reload && chmod +x ~/.config/waybar/scripts/get_weather.sh"]

[profiles.sway.dots]
sway = { source = "sway/config", target = ".config/sway" }
waybar = { source = "sway/waybar", target = ".config/waybar" }
mako = { source = "sway/mako", target = ".config/mako" }
wofi = { source = "sway/wofi", target = ".config/wofi" }
onagre = { source = "sway/onagre", target = ".config/onagre" }